### ISSUE TITLE
jquery-ui-i18n.min

### ISSUE THREAD

**Issue by merlincom** [axllent/jquery#1]
Thank you Ralph for your helfull tool

would be happy if I could install the jquery-ui-i18n.min file at the same time as the Composer. I need this file in all my projects for formatting the datepicker in JQueryUi. What do you think of this idea and would it be possible?

PS: However, I am aware that attaching a file that is used by JQueryUI is not consistent in a certain sense. 
Greetings from Marcel

**Comment by axllent** [comment]
HI @merlincom. I'm afraid the jQuery UI is a completely different package which has nothing to do with jQuery itself (other than that it uses jQuery extensively) so it won't ever be part of this repository.

I suspect that what you are looking for can be found in [components/jqueryui](https://github.com/components/jqueryui) (`composer require components/jqueryui`) - you may want to first explore that repository to ensure what you need is included (I do not use Query UI but I do know there are a lot of files included there for the various UI elements).

Hope this helps!
